#!/usr/bin/env ruby
banner = <<-BANNER
Usage: add-collaborators [<issue URL> or options]
BANNER

# add as collaborators anyone who comments on a given issue in a given repo
# assumes you store the appropriate OAuth token as an ENV variable called GITHUBTEACHER_TOKEN

require 'octokit'
require 'optparse'
require 'spreadsheet'
require_relative 'common'


access_token = ENV['GITHUBTEACHER_TOKEN'] or abort("You need a GitHub Teacher access token")
repo_name, issue_num = nil, nil

s = spreadsheet::Workbook.read("hubber.xlsx")
s.selected_sheet = s.sheets.first
s.first_row.upto(s.last_row) do |line|
  cell_data = s.columns(2)
end


# Make sure arguments are specified
ARGV << '-h' if ARGV.empty?

ARGV.options do |opts|
  opts.banner = banner
  opts.on("-r", "--repo REPOSITORY", String) { |val| repo_name = training-utils}
  opts.on_tail("-h", "--help")               { abort opts.to_s }
  opts.parse!
end

# Create a new Octokit Client
Octokit.auto_paginate = true
client = Octokit::Client.new :access_token => access_token

# Save a little time - build a hash of current collaborators so we can skip them later
current_collaborators = Hash[client.collaborators(repo_name).map { |collaborator|
  [collaborator[:login], collaborator[:login]]
}]

# Get handles from excel and Add as Collaborators
successfully_added_users = []
begin
    username = cell_data
    next if current_collaborators[username] # skip adding if already a collaborator
    if user_added = client.add_collaborator(repo_name, username)
      successfully_added_users << username
    else
      puts "Failed to add #{username} as a collaborator (check: is githubteacher repository owner?)"
    end
  end
rescue Octokit::NotFound
  abort "[404] - Repository not found:\nIf #{repo_name || "nil"} is correct, are you using the right Auth token?"
rescue Octokit::UnprocessableEntity
  abort "[422] - Unprocessable Entity:\nAre you trying to add collaborators to an org-level repository?"
end

if successfully_added_users.any?
  begin
    names = "@#{successfully_added_users.first}"
    verb  = "is"
    num   = "a"
    noun  = "collaborator"

    if successfully_added_users.size > 1
      verb  = "are"
      num   = ""
      noun  = "collaborators"

      if successfully_added_users.size == 2
        names = "@#{successfully_added_users.first} and @#{successfully_added_users.last}"
      else
        at_mentions = successfully_added_users.map { |name| "@#{name}" }
        names = "#{at_mentions[0...-1].join(", ")}, and #{at_mentions[-1]}"
      end
    end

    message = ":tada: #{names} #{verb} now #{num} repository #{noun}. :balloon:"
    client.add_comment repo_name, issue_num, message
  rescue => e
    abort "ERR posting comment (#{e.inspect})"
  end
end
